package com.jberry.dto;


//impliments?
public class Food {
    int id;
    String Nafn;
    String Fæðuflokkur;
    String Name;
    String Aðalfl;
    String Undirfl;
    float Æturhluti;
    float Mettaðarfitusýrur;
    float cisEinómettaðarfitusýrur;
    float cisFjölómettaðarfitusýrur;
    float cisFjölómettaðarfitusn3langar;
    float transFitusýrur;
    float Kolvetnialls;
    float Sykrur;
    float Viðbættursykur;
    float Trefjaefni;
    float Steinefnialls;
    float AvítamínRJ;
    float Retinol;
    float EvítamínalfaTJ;
    float Níasínjafngildi;
    float Níasín;
    float Fólatalls;
    float Fosfór;
    float Selen;
    float cisFjölómettaðarfitusn6;
    float cisFjölómettaðarfitusn3;
    float Prótein;
    float Fita;
    float transfita;
    float Kólesteról;
    float Kolvetni;
    float Sykur;
    float Alkohól;
    float Vatn;
    float Avítamín;
    float Dvítamín;
    float Evítamín;
    float B1vítamín;
    float B2vítamín;
    float B6vítamín;
    float B12vítamín;
    float Cvítamín;
    float Kalk;
    float Fosfor;
    float Magnesíum;
    float Járn;
    float Sink;
    float Natríum;
    int Kalíum;
    float Kopar;
    float Joð;
    float Betakarótín;
}
